api.info.title=API Académica
api.info.description=Microservicio para gestión de estudiantes y titulaciones
api.info.contact.name=Joaquin Murcia Escanez
api.info.contact.email=jme418@inlumine.ual.es
api.info.contact.url=https://github.com/jme418-ual/
api.info.version=1.0.0
